### ISSUE TITLE
retrieve users following list + followers list

### ISSUE THREAD

**Issue by swongg** [Lakshya021/cpsc455-project#21]
- backend endpoint(s) for retrieving a user's followers list and a user's followings list

**Comment by Lakshya021** [comment]
this would just be retrieving the user's data. we don't need separate endpoints for this.

Can we close this ? unless im missing something

**Comment by swongg** [comment]
Yes, you're right. Discussed with Daniel as well on Slack. We don't need this endpoint since the ```getUsers``` endpoint will already return all the info associated with a user
