### ISSUE TITLE
Retrieve user profile endpoint

### ISSUE THREAD

**Issue by swongg** [Lakshya021/cpsc455-project#32]
- retrieve a specific user profile based on the query which was passed (maybe it will be the userid)
- New Note: We need to update the existing user schema to include userbio, profile image url, username etc.

**Comment by Lakshya021** [comment]
@danielcrookall this was completed by me in one of the PRs

**Comment by danielcrookall** [comment]
> @danielcrookall this was completed by me in one of the PRs

This was completed a while ago and is already merged into main. There are 2 endpoints, one for  user id, one for usernames/suggestedusers.
![image](https://user-images.githubusercontent.com/83941101/179445487-65373315-8bf1-412f-a4fc-83938c767af2.png)

**Comment by Lakshya021** [comment]
@danielcrookall you are right, I forgot about this. I might have implemented it at the moment because your branch might not have been merged.
